---
title: "R Notebook"
# output: html_notebook
editor_options: 
  chunk_output_type: console
output: 
  html_notebook: 
    fig_caption: yes
fig_width: 6 
fig_height: 4 
---

# Load libraries
```{r}
library(FIELDimageR)
library(raster)
library(rgdal)
```

# Process all orthomosaics
```{r}
# Set the path to the "downsampled_orthos" folder
folder_path <- "downsampled_orthos"

# Get a list of all files ending in "_downsample.tif"
files <- list.files(path = folder_path, pattern = "_downsample\\.tif$")

# Iterate through the files
for (ortho_path in files) {
  
  # Remove the ".tif" substring from the ortho_path string
  result <- gsub(".tif", "", ortho_path, fixed = TRUE)
  
  # Print the result
  print(result)
  
  # Open the orthomosaic
  EX1 <- stack(file.path(folder_path, ortho_path))
  # EX1<-aggregate(EX1, fact=4)
  # plotRGB(EX1, r = 1, g = 2, b =3)

  # Remove soil pixels
  EX1.RemSoil <- fieldMask(mosaic = EX1, Red = 1, Green = 2, Blue = 3, index = "HUE")

  # Open shapefile and add to the orthomosaic
  fieldshape <- readOGR(dsn = "shapefile/F120_beans_2023_rotated_qgis_updated.shp", layer = "F120_beans_2023_rotated_qgis_updated")
  EX1.Shape <- fieldshape

  # Calculate canopy cover
  EX1.Canopy<-fieldArea(mosaic = EX1.RemSoil$mask, fieldShape = EX1.Shape, n.core = 5)

  # Calculate vegetation indices
  EX1.Indices<- fieldIndex(mosaic = EX1.RemSoil$newMosaic, Red = 1, Green = 2, Blue = 3,
                          index = c("NGRDI","BGI", "GLI", "BI", "SI", "VARI"),
                          plot = FALSE)

  # Visualize the indices
  EX1.Info<- fieldInfo(mosaic = EX1.Indices,fieldShape = EX1.Shape, n.core = 5)
  fieldPlot(fieldShape=EX1.Info$fieldShape,fieldAttribute="VARI", mosaic=EX1, color=c("red","blue"), alpha = 0.5)

  # Combine inidices and canopy cover
  indices_data <- EX1.Info$plotValue
  canopy_cover_data <- EX1.Canopy$areaPorcent

  # Get the row names of the dataframes
  indices_data$index <- row.names(indices_data)
  canopy_cover_data$index <- row.names(canopy_cover_data)

  # Merge the dataframes using the index column
  merged_data <- merge(indices_data, canopy_cover_data, by = "index")

  # Remove the index column from the merged dataframe
  merged_data$index <- NULL

  # Using the subset function
  merged_data <- subset(merged_data, select = -5)

  # Add ".csv" to the end of the result string
  result <- paste0(result, ".csv")

  # Save output to file
  write.csv(merged_data, file = result, row.names = FALSE)
  
  rm(result, EX1, indices_data, canopy_cover_data, merged_data)
  
}
```